// @ts-check
/**
 * A small ruleset, on purpose.
 *
 * This exists to catch mistakes that survive `tsc` — an unused import, a
 * floating `any`, a React hook called conditionally — and to stop new drift.
 * It is not here to relitigate how the existing code is written: the codebase
 * is hand-wrapped rather than machine-formatted, and a lint pass that
 * reformatted 185 files would bury every real finding underneath it.
 *
 * So: the recommended sets, a handful of deliberate relaxations where the
 * existing architecture is right and the default rule is wrong for it, and
 * eslint-config-prettier last so nothing here has an opinion about whitespace.
 */
const js = require('@eslint/js');
const tseslint = require('typescript-eslint');
const reactHooks = require('eslint-plugin-react-hooks');
const prettier = require('eslint-config-prettier');
const globals = require('globals');

module.exports = tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/.wrangler/**',
      'apps/api/.worker-build/**',
      // Generated by wrangler; not ours to lint.
      '**/worker-configuration.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  /* ── TypeScript everywhere ─────────────────────────────────────────── */
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: { ecmaVersion: 2022, sourceType: 'module' },
      globals: { ...globals.node },
    },
    rules: {
      // An unused parameter is usually a signature being satisfied — Nest
      // middleware, Express handlers, jest mocks. An underscore says so.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // The pg driver hands back untyped rows and the Worker entry crosses a
      // runtime boundary tsc cannot describe. `any` is a smell, not a defect,
      // and erroring on it here would mean noise rather than fixes.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  /* ── The API ───────────────────────────────────────────────────────── */
  {
    files: ['apps/api/**/*.ts'],
    rules: {
      // Nest injects by decorator metadata, so an "unused" constructor
      // parameter property is the entire point of the declaration.
      'no-empty-function': 'off',
      '@typescript-eslint/no-empty-function': 'off',
    },
  },

  /* ── The SPAs ──────────────────────────────────────────────────────── */
  {
    files: ['apps/tenant-web/**/*.{ts,tsx}', 'apps/admin-web/**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // The one class of React bug that is silent, intermittent, and
      // impossible to reason about from the symptom.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  /* ── Node scripts, migrations and Worker shims (CommonJS) ──────────── */
  {
    files: [
      'scripts/**/*.js',
      'apps/api/scripts/**/*.{js,cjs,mjs}',
      'apps/api/migrations/**/*.js',
      // Hand-written CommonJS that the Worker bundler substitutes for
      // packages a Worker cannot run. Not application code, but ours.
      'apps/api/worker/**/*.{js,cjs}',
      'eslint.config.js',
      '*.config.js',
      '**/jest*.config.js',
    ],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: {
      // These ARE the command-line tools. Printing is what they do.
      'no-console': 'off',
      // CommonJS is the point of these files, not an oversight.
      '@typescript-eslint/no-require-imports': 'off',
      // Same underscore convention as the TypeScript side. The Worker stubs
      // exist precisely to accept arguments and ignore them.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  /* ── ESM build tooling ─────────────────────────────────────────────── */
  {
    files: ['**/*.mjs'],
    languageOptions: {
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: { 'no-console': 'off' },
  },

  /* ── Tests ─────────────────────────────────────────────────────────── */
  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/*.itest.ts'],
    languageOptions: { globals: { ...globals.jest } },
    rules: {
      // A test mocks a service by asserting a shape it does not have.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // Last: turns off everything that merely disagrees with Prettier.
  prettier,
);
